metrics: true
exp-drop-chance: 2.0
exp-drop-amount: 1

drop-settings-inventory-size: 36

drop-sound: BLOCK_DISPENSER_DISPENSE
drop-message: "&eDrop &8► &7wydropiłeś/aś &d%item% &fx&7%amount%"
turbo-drop-message: "&cTurbo Drop &7został uruchomiony przez &e%player% &7na &e%minutes% minut!"

enabled-worlds:
  - "world"
  - "custom_world"

# - "PERMISSION ; MULTIPILER"
drop-multipiler:
  - "owndrop.multipiler.vip;1.1"
  - "owndrop.multipiler.svip;1.2"

drop-options-gui-title: "&e&lDrop &8» &4Opcje"
drop-settings-gui-title: "&e&lDrop &8» &4Ustawienia"
drop-menu-gui-title: "&e&lDrop &8» &4Menu"

drop-menu-gui-fill-item-material: BLUE_STAINED_GLASS_PANE
drop-settings-gui-fill-item-material: BLUE_STAINED_GLASS_PANE

check-mark: "&a✔"
cross-mark: "&4x"

drop-item-lore:
  - "&7Szansa: &e%chance%%"
  - "&7Ilosc: &ex%amount%"
  - "&7Status: %status%"

main-menu-gui-items:
  drop-settings-item:
    material: BEACON
    name: "&7Ustawienia &eDropu"
    lore:
      - "&eKliknij, aby zobaczyc ustawienia dropu ze stone."
  drop-options-item:
    material: STONE_PICKAXE
    name: "&7Opcje &eDropu"
    lore:
      - "&eKliknij, aby zobaczyc opcje dropu ze stone."
  turbo-drop-item:
    material: DIAMOND_PICKAXE
    name: "&7Turbo &cDrop"
    lore:
      - "&7Status: %status%"

drop-settings-gui-items:
  exp-drop:
    material: EXPERIENCE_BOTTLE
    name: "&7Drop EXPa"
    lore:
      - "&7Status: %status%"
  messages:
    material: PAPER
    name: "&7Wiadomosci"
    lore:
      - "&7Status: %status%"
  sounds:
    material: NOTE_BLOCK
    name: "&7Dzwieki"
    lore:
      - "&7Status: %status%"
  cobblestone-drop:
    material: COBBLESTONE
    name: "&7Drop Cobblestone"
    lore:
      - "&7Status: %status%"

drop-options-gui-items:
  enable-all:
    material: LIME_WOOL
    name: "&aWlacz wszystko"
    lore:
      - "&7Kliknij, aby &awlaczyc&7 wszystkie dropy"
  disable-all:
    material: RED_WOOL
    name: "&cWylacz wszystko"
    lore:
      - "&7Kliknij, aby &cwylaczyc&7 wszystkie dropy"