name: OwnDrop
main: me.symi.owndrop.Main
author: Symi
version: 1.1
api-version: 1.15
website: https://owncraft.eu

commands:
  drop:
    aliases: [owndrop]
    description: Opens drop GUI menu
  turbo:
    aliases: [ownturbo]
    description: Turbo drop enable command

permissions:
  owndrop.turbo.enable:
    description: Permission for turbo drop enable command
    default: op
  owndrop.reload:
    description: Permission for drop reload command
    default: op